export const ROLES = {
  ADMIN: "admin",
  STAFF: "staff",
  STUDENT: "student",
};

export const PERMISSIONS = {
  // Book Management
  MANAGE_BOOKS: [ROLES.ADMIN],
  VIEW_BOOKS: [ROLES.ADMIN, ROLES.STAFF, ROLES.STUDENT],
  
  // User Management
  MANAGE_USERS: [ROLES.ADMIN],
  VIEW_USERS: [ROLES.ADMIN],
  
  // Borrowing & Returns
  ISSUE_BOOKS: [ROLES.ADMIN, ROLES.STAFF],
  RETURN_BOOKS: [ROLES.ADMIN, ROLES.STAFF],
  BORROW_BOOKS: [ROLES.STUDENT],
  
  // Reports & Analytics
  VIEW_REPORTS: [ROLES.ADMIN],
  GENERATE_REPORTS: [ROLES.ADMIN],
  
  // System Settings
  MANAGE_SETTINGS: [ROLES.ADMIN],
  
  // Fine Management
  MANAGE_FINES: [ROLES.ADMIN],
  VIEW_FINES: [ROLES.ADMIN, ROLES.STUDENT],
  
  // Common permissions
  EVERYONE: [ROLES.ADMIN, ROLES.STAFF, ROLES.STUDENT],
  STAFF_LEVEL: [ROLES.ADMIN, ROLES.STAFF],
  ADMIN_ONLY: [ROLES.ADMIN],
};
